metric: COCO
num_classes: 13

TrainDataset:
  !COCODataSet
    image_dir: E:\CAR\test\images\train_img
    anno_path: E:\CAR\test\train.json
    dataset_dir: E:\CAR\test
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: E:\CAR\test\images\val_img
    anno_path: E:\CAR\test\val.json
    dataset_dir: E:\CAR\test

TestDataset:
  !ImageFolder
    anno_path: E:\CAR\test\train.json
    dataset_dir: E:\CAR\test
